#### 1. Import the numpy package under the name `np`

In [2]:
import numpy as np

#### 2. Create a null vector of size 10 (★☆☆)

In [3]:
a = np.zeros(10)
a

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 3. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [4]:
a[4] = 1
a

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

#### 4. Create a vector with values ranging from 10 to 49 (★☆☆)

In [5]:
b = np.arange(50)
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

#### 5. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [6]:
c = np.arange(9).reshape(3,3)
c

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 6. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [7]:
np.nonzero([1,2,0,0,4,0])

(array([0, 1, 4], dtype=int64),)

#### 7. Create a 3x3 identity matrix (★☆☆)

In [8]:
matrix1 = np.eye(3)
matrix1

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 8. Create a 3x3x3 array with random values (★☆☆)

In [9]:
np.random.seed(123)
d = np.random.random((3,3,3))
d

array([[[0.69646919, 0.28613933, 0.22685145],
        [0.55131477, 0.71946897, 0.42310646],
        [0.9807642 , 0.68482974, 0.4809319 ]],

       [[0.39211752, 0.34317802, 0.72904971],
        [0.43857224, 0.0596779 , 0.39804426],
        [0.73799541, 0.18249173, 0.17545176]],

       [[0.53155137, 0.53182759, 0.63440096],
        [0.84943179, 0.72445532, 0.61102351],
        [0.72244338, 0.32295891, 0.36178866]]])

#### 9. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [10]:
e = np.random.random((10,10))
e

array([[0.22826323, 0.29371405, 0.63097612, 0.09210494, 0.43370117,
        0.43086276, 0.4936851 , 0.42583029, 0.31226122, 0.42635131],
       [0.89338916, 0.94416002, 0.50183668, 0.62395295, 0.1156184 ,
        0.31728548, 0.41482621, 0.86630916, 0.25045537, 0.48303426],
       [0.98555979, 0.51948512, 0.61289453, 0.12062867, 0.8263408 ,
        0.60306013, 0.54506801, 0.34276383, 0.30412079, 0.41702221],
       [0.68130077, 0.87545684, 0.51042234, 0.66931378, 0.58593655,
        0.6249035 , 0.67468905, 0.84234244, 0.08319499, 0.76368284],
       [0.24366637, 0.19422296, 0.57245696, 0.09571252, 0.88532683,
        0.62724897, 0.72341636, 0.01612921, 0.59443188, 0.55678519],
       [0.15895964, 0.15307052, 0.69552953, 0.31876643, 0.6919703 ,
        0.55438325, 0.38895057, 0.92513249, 0.84167   , 0.35739757],
       [0.04359146, 0.30476807, 0.39818568, 0.70495883, 0.99535848,
        0.35591487, 0.76254781, 0.59317692, 0.6917018 , 0.15112745],
       [0.39887629, 0.2408559 , 0.3434560

#### 10. Create a random vector of size 30 and find the mean value (★☆☆)

In [11]:
f = np.random.random(30)
np.mean(f)

0.5078714702038956

#### 11. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [12]:
matrix2 = np.diag([1,2,3,4,5])
matrix2

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

#### 12. Normalize a 5x5 random matrix (★☆☆)

In [13]:
np.random.normal(matrix2)

array([[ 1.33786152,  0.66752096, -1.90931822, -1.84400643,  0.37383405],
       [ 1.5097338 ,  2.15947411, -0.80072783, -0.53904475,  1.04161958],
       [ 0.09443589,  0.1610524 ,  4.54095031,  0.45353229, -0.28715592],
       [-1.03189998,  1.62132343, -1.97245673,  3.75932049, -0.3044812 ],
       [-0.13973321,  1.36031756,  0.74107327,  0.08851851,  3.64660368]])

#### 13. How to find common values between two arrays? (★☆☆)

In [14]:
np.intersect1d(matrix1, matrix2)

array([0., 1.])

#### 14. Create a random vector of size 10 and sort it (★★☆)

In [15]:
np.sort(np.random.random(10))

array([0.02931972, 0.03219793, 0.12175436, 0.37898585, 0.472913  ,
       0.54263593, 0.63590036, 0.66838395, 0.71775756, 0.74478066])

#### 15. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [16]:
np.random.seed(123)
g = np.random.random(10)
g

array([0.69646919, 0.28613933, 0.22685145, 0.55131477, 0.71946897,
       0.42310646, 0.9807642 , 0.68482974, 0.4809319 , 0.39211752])

In [17]:
g[np.argmax(f)] = 0
g

array([0.69646919, 0.28613933, 0.22685145, 0.55131477, 0.71946897,
       0.42310646, 0.9807642 , 0.        , 0.4809319 , 0.39211752])

#### 16. Subtract the mean of each row of a matrix (★★☆)

In [18]:
matrix2 - np.mean(matrix2)

array([[ 0.4, -0.6, -0.6, -0.6, -0.6],
       [-0.6,  1.4, -0.6, -0.6, -0.6],
       [-0.6, -0.6,  2.4, -0.6, -0.6],
       [-0.6, -0.6, -0.6,  3.4, -0.6],
       [-0.6, -0.6, -0.6, -0.6,  4.4]])

#### 17. How to get the n largest values of an array (★★★)

In [19]:
z = np.arange(10000)
np.random.shuffle(z)

n=5
z[np.argsort(z)[len(z)-n]]

9995

#### 18. Create a random 5*3 matrix and replace items that are larger than 4 by their squares ( Example:  6 --> 36) 

In [31]:
h = np.random.randint(0,10,(5,3))
h

array([[5, 5, 7],
       [3, 4, 0],
       [9, 8, 9],
       [2, 1, 8],
       [0, 6, 6]])

In [33]:
np.where(h>4, h**2, h)

array([[25, 25, 49],
       [ 3,  4,  0],
       [81, 64, 81],
       [ 2,  1, 64],
       [ 0, 36, 36]])